version: "3"
services:
  client:
    image: "jurisbandenieks/booking-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "jurisbandenieks/booking-server"
    mem_limit: 128m
    hostname: api
  nginx:
    image: "jurisbandenieks/booking-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
