version: "3"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - DATABASE_URL=postgres://postgres:postgres_password@postgres:5432/postgres
  auth:
    depends_on:
      - api
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./auth
    volumes:
      - /app/node_modules
      - ./auth:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - NODE_ENV=development
    ports:
      - "5001:5001"
  client:
    depends_on:
      - api
      - auth
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
