FROM node:16-alpine
WORKDIR "/app"
COPY ./package.json ./
COPY ./tsconfig.json ./
RUN npm install
COPY . .
# Install node-pg-migrate globally
RUN npm install -g node-pg-migrate
CMD ["sh", "-c", "npm run start:dev"]